[project]
name = "kivy_glow"
version = "1.0.5"
authors = [
  {name="Leonid Gvozdev", email="leo.gvozdev.dev@gmail.com"},
]
description = "Kivy widget set"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Operating System :: Android",
    "Operating System :: POSIX :: Linux",
    "Operating System :: POSIX :: BSD :: FreeBSD",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: iOS",
    "Operating System :: MacOS",
    "Operating System :: MacOS :: MacOS X",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Visualization"
]

[project.urls]
"Homepage" = "https://github.com/GvozdevLeonid/KivyGlow"
"Bug Tracker" = "https://github.com/GvozdevLeonid/KivyGlow/issues"

[build-system]
requires = [
    "kivy>=2.3.0",
    "setuptools",
    "requests",
    "pillow",
    "wheel",
]
