[build-system]
requires = ["pip>=22.3.1",
    "setuptools>=66.0.0",
    "wheel>=0.38.4"]

build-backend = "setuptools.build_meta"

[project]
name = "sb-orm-lite"
readme = "README.md"
version = "0.0.3"
authors = [
    { name = "Stephen Booth", email = "stephen.booth.za@gmail.com" },
]
description = "A lightweight orm implementation"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["sb-db-common>=0.0.1",
    "mysql-connector-python~=8.1.0",
    "psycopg2~=2.9.9",
    "sb-db-common>=0.0.1",
    "pymongo~=4.10.1",
    "sb-serializer~=0.0.3"]
