[project]
name = "sche_YOUR_USERNAME_HERE"
version = "0.0.1"
authors = [
    { name="Akshit Shubham", email="akshit@1471bl.onmicrosoft.com" },
]
description = "A small schema package for database uses."
#readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.setuptools]
py-modules = []
