[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pagos"
version = "0.1.1"
authors = [
  { name="Stanley Scott", email="sscott@iup.uni-heidelberg.de" },
  { name="Chiara Hubner" },
]
description = "Python Analysis of Groundwater and Ocean Samples"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/nompynuthead/VACAO_Stan_Chiara"