[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"


[project]
name = "jrmpc"
version = "0.1.3"
dependencies = [
  "numpy",
  "tqdm",
  "typing-extensions ; python_version < '3.10'"
]
requires-python = ">=3.7"
authors = [
  { name="Luc Vedrenne", email="vedrenne@unistra.fr" },
]
description = "Numpy & PyTorch implementation of the JRMPC algorithm."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
Repository = "https://github.com/ListIndexOutOfRange/JRMPC-PyTorch"


# python3 -m build
# twine check dist/*
# twine upload dist/*