[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ezserve"
dependencies = ["bottle>=0.13.1"]
version = "0.2.0"
authors = [
    { name="Farm-Art", email="github@farmart.tech" },
]
description = "A simple way to share files over HTTP without explaining FTP to the receiver."
readme = "README.md"
requires-python = ">=3.12"
license.file = "LICENSE"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["server", "serve", "easy", "http", "cli"]

[project.urls]
Homepage = "https://github.com/Farm-Art/EZserve"
Issues = "https://github.com/Farm-Art/EZserve/issues"
