[tool.poetry]
name = "battery-advisor"
version = "1.2.0"
description = "A simple tool to monitor and notify about battery status. Built with Python."
authors = ["fer-hnndz <65425622+fer-hnndz@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/fer-hnndz/battery-advisor"
keywords = ["battery", "monitor", "notify"]
include = ["defaultSettings.toml", "icon.png", "LICENSE"]


[tool.poetry.dependencies]
python = "^3.11"
pystray = "^0.19.5"
toml = "^0.10.2"
psutil = "^6.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
battery-advisor = "battery_advisor:entry.cli"
