[project]
name = "dekmedia"
version = "0.1.6"
description = ""
authors = [
    { name = "sanzenwin", email = "sanzenwin@gmail.com" },
]
dependencies = [
    "dektools[yaml]<1.0.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]
audio = [
    "just-playback<=0.1.8",
]
image = [
    "pillow<=10.3.0",
]
svg = [
    "svglib<=1.5.1",
    "pymupdf<=1.22.5",
    "svgpathtools<=1.6.1",
]

[project.scripts]
dekmedia = "dekmedia.click.__entry__:main"

[tool.pdm.build]
includes = [
    "dekmedia",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
