[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "eo4eu_comm_utils",
    "eo4eu_comm_utils.kafka",
    "eo4eu_comm_utils.comms",
    "eo4eu_comm_utils.format",
]

# [project.scripts]
# post-pro = "post_pro.app:run"
# test-post-pro = "post_pro.test.dummy_app:run"

[project]
name = "eo4eu_comm_utils"
version = "0.6.2"
authors = [
    {name = "Apollon Grigoras", email = "apollon@uoa.gr"},
]
description = "General messaging utilities for EO4EU"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "confluent-kafka==2.1.1",
    "prometheus-client==0.16.0",
    "setuptools==65.5.1",
]
