[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "refer-agents"
version = "0.1.2"
authors = [
  { name="Yaswanth Narsupalli", email="yasshu.yaswanth@gmail.com" },
  { name="Sreevatsa Muppirala", email="sreevatsa2002@gmail.com" },
]
description = "ReFeR: Improving Evaluation and Reasoning through Hierarchy of Models"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "openai==1.50.2",
    "mistralai==1.1.0",
    "google-generativeai==0.8.2",
    "groq==0.11.0",
    "together==1.3.0",
    "pillow",
    "tqdm==4.66.5",
    "asyncio==3.4.3",
    "regex==2024.9.11",
]

[project.urls]
"Homepage" = "https://github.com/yaswanth-iitkgp/ReFeR"
"Bug Tracker" = "https://github.com/yaswanth-iitkgp/ReFeR/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["refer_agents*"]
namespaces = false

[tool.setuptools.package-data]
"ReFeR" = ["*.json", "*.md"]
