[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pratik"
version = "1.2.2"
authors = [
  { name="Axelle V.", email="lassa.inora@gmail.com" },
]
description = "A library of various functions and classes helping to program more efficiently and more intuitively"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/LassaInora/Pratik"
"Bug Tracker" = "https://github.com/LassaInora/Pratik/issues"