[project]
name = "server-status"
dynamic = []
description = "Server status client"
authors = [
    { name = "snowykami", email = "snowykami@outlook.com" },
]
dependencies = [
    "requests>=2.32.3",
    "psutil>=6.0.0",
    "arclet-alconna>=1.8.30",
]
requires-python = ">=3.11"
readme = "README.md"
version = "1.0.5"

[project.license]
text = "MIT"

[project.scripts]
server-status = "server_status.__main__:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "scm"
tag_filter = "v*"
tag_regex = "^v(?:\\D*)?(?P<version>([1-9][0-9]*!)?(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))*((a|b|c|rc)(0|[1-9][0-9]*))?(\\.post(0|[1-9][0-9]*))?(\\.dev(0|[1-9][0-9]*))?$)$"
