[tool.poetry]
name = "volttron-listener"
version = "2.0.0rc0"
description = "The volttron-listener agent allows publishing of message bus traffic to standard out."
authors = ["VOLTTRON Team <volttron@pnnl.gov>"]
license = "Apache License 2.0"
readme = "README.md"
repository = "https://github.com/eclipse-volttron/volttron-listener"
homepage = "https://github.com/eclipse-volttron/volttron-listener"
keywords = []
packages = [ { include = "listener", from = "src" } ]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: Apache Software License"
]
[tool.poetry.dependencies]
python = "^3.10"
volttron-core = ">=2.0.0rc0"

# [tool.poetry.group.dev.dependencies]
# # formatting, quality, tests
# pytest = "^6.2.5"
# mock = "^4.0.3"
# pre-commit = "^2.17.0"
# yapf = "^0.32.0"
# toml = "^0.10.2"
# isort = "^5.10.1"
# safety = "^1.10.3"
# mypy = "^0.942"
# coverage = "^6.3.2"
# pytest-cov = "^3.0.0"
# Sphinx = "^4.5.0"
# sphinx-rtd-theme = "^1.0.0"
# volttron-core = "^1.1.0"

[tool.yapfignore]
ignore_patterns = [
    ".venv/**",
    ".pytest_cache/**",
    "dist/**",
    "docs/**"
]

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
column_limit = 120
split_before_logical_operator = true

[tool.poetry.scripts]
volttron-listener-agent = "listener.agent:main"

[build-system]
requires = ["poetry-core>=1.2.2"]
build-backend = "poetry.core.masonry.api"
