# This file is placed in the Public Domain.

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nixt"
version = "60"
authors = [
    {name = "Bart Thate", email = "record11719@gmail.com" },
]
description = "You have been nixt."
readme = "README.rst"
license = { text="Public Domain"}
classifiers=[
    'Development Status :: 4 - Beta',
    'License :: Public Domain',
    'Operating System :: Unix',
    'Programming Language :: Python :: 3',
    'Topic :: Utilities'
]

[project.urls]
"home" = "https://pypi.org/project/nixt"
"bugs" = "https://github.com/otpcr/nixt/issues"
"source" = "https://github.com/otpcr/nixt"

[tool.setuptools]
script-files = [
   'bin/nixt',
   'bin/nixtc',
   'bin/nixtd',
   'bin/nixts'
]   
packages = [
   'nixt',
   'nixt.modules'
]

[tool.setuptools.data-files]
"share/doc/nixt/" =  [
    'files/RECONSIDER.rst',
    'files/bevestigd.jpg',
    'files/bevestigd.pdf',
    'files/informed.jpg',
    'files/EM_Ack_OTP-CR-117_19.pdf',
    'files/EM_T04_OTP-CR-117_19.pdf',
    'files/EM_T07_OTP-CR-117_19_001.pdf',
    'files/Kamer.pdf'
]
